baseurl: ""
# markdown: kramdown
# kramdown:
#   parse_block_html: true
#   hard_wrap: false
nav:
  - DeviCat: /devicat
  - CandiCat: /candicat
  - Events: /events
  - Newsletter: /newsletter
  - Portfolio:
      - Art: /gallery
      - Catalog: /catalog
  - Shop: 
        - DAC Candi Cat: https://www.amazon.com/DIAMOND-ART-CLUB-Painting-Beginners/dp/B0F4M34J2X?th=1
        - DAC Plushie Catcher: https://www.amazon.com/DIAMOND-ART-CLUB-Plushie-Catcher/dp/B0GZ12LVWQ
        - DAC Candy Drop: https://www.amazon.com/DIAMOND-ART-CLUB-Diamond-Adults/dp/B0HCR7HS88
        - Fourthwall: https://devicat-shop.fourthwall.com
excerpt_separator: <!--card-->